namespace: "kubevirt"
registry_url: "docker.io"
registry_namespace: "kubevirt"
docker_prefix: "{{ registry_url }}/{{ registry_namespace }}"

platform: "openshift"

apb_action: "provision"
kubevirt_template_dir: "{{ role_path }}/templates"
version: 0.12.0-alpha.2
docker_tag: "v{{ version }}"
image_pull_policy: IfNotPresent

offline_template_dir: "/opt/apb/kubevirt-templates"
common_templates_version: "0.3.2"

default_vm_templates:
  - "vm-template-fedora"
  - "vm-template-windows2012r2"
  - "vm-template-rhel7"
kubevirt_privileged_policies:
  - kubevirt-privileged
  - kubevirt-controller
  - kubevirt-infra  # For KubeVirt v0.2.0
  - kubevirt-apiserver
